apiVersion: apps/v1
kind: Deployment
metadata:
  name: automotive-dev-webui
  namespace: automotive-dev-operator-system
  labels:
    app.kubernetes.io/name: automotive-dev-webui
    app.kubernetes.io/part-of: automotive-dev-operator
    app.kubernetes.io/component: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: automotive-dev-webui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: automotive-dev-webui
        app.kubernetes.io/part-of: automotive-dev-operator
        app.kubernetes.io/component: webui
    spec:
      containers:
      - name: webui
        image: quay.io/rh-sdv-cloud/aib-webui:latest
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
          capabilities:
            drop:
            - ALL
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nginx-config
        configMap:
          name: webui-nginx-config
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}