apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- route.yaml
configMapGenerator:
- files:
  - nginx.conf
  name: webui-nginx-config


images:
- name: quay.io/rh-sdv-cloud/aib-webui
  newTag: latest
labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: automotive-dev-webui
    app.kubernetes.io/part-of: automotive-dev-operator
