apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlan
metadata:
  name: automotive-dev-operator-dev
  namespace: default
  labels:
    release.appstudio.openshift.io/auto-release: "true"
spec:
  application: automotive-dev-operator
  target: dev-environment
  
  # Auto-release on every successful build to main branch
  policy:
    - name: automotive-dev-operator-policy
  
  # Pipeline to execute for release
  pipeline:
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: https://github.com/centos-automotive-suite/automotive-dev-operator
        - name: revision
          value: main
        - name: pathInRepo
          value: .tekton/release-pipeline.yaml
    
    params:
      - name: release-strategy
        value: dev
      - name: snapshot
        value: "{{snapshot}}"
      - name: target-namespace
        value: automotive-dev-operator-dev
  
  releaseGracePeriodDays: 7

