openapi: 3.0.3
info:
  title: Image Catalog API
  description: REST API for managing automotive OS image catalog
  version: v1alpha1
  contact:
    name: Automotive Dev Operator
    url: https://github.com/centos-automotive-suite/automotive-dev-operator

servers:
  - url: /api/v1alpha1/catalog
    description: Image catalog API endpoints

paths:
  /images:
    get:
      summary: List catalog images
      description: Retrieve a list of images from the catalog with optional filtering
      operationId: listCatalogImages
      parameters:
        - name: namespace
          in: query
          description: Kubernetes namespace to filter by
          schema:
            type: string
        - name: architecture
          in: query
          description: Filter by CPU architecture
          schema:
            type: string
            enum: [amd64, arm64]
        - name: distro
          in: query
          description: Filter by distribution
          schema:
            type: string
            example: cs9
        - name: target
          in: query
          description: Filter by hardware target
          schema:
            type: string
            example: raspberry-pi
        - name: phase
          in: query
          description: Filter by availability phase
          schema:
            type: string
            enum: [Pending, Verifying, Available, Unavailable, Failed]
        - name: tags
          in: query
          description: Filter by tags (comma-separated)
          schema:
            type: string
            example: "production,automotive"
        - name: limit
          in: query
          description: Maximum number of results to return
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
        - name: continue
          in: query
          description: Continuation token for pagination
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogImageList'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create catalog image
      description: Add a new image to the catalog
      operationId: createCatalogImage
      parameters:
        - name: namespace
          in: query
          description: Kubernetes namespace for the image
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCatalogImageRequest'
      responses:
        '201':
          description: Image successfully added to catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogImage'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Image already exists in catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /images/{name}:
    get:
      summary: Get catalog image details
      description: Retrieve detailed information about a specific catalog image
      operationId: getCatalogImage
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the catalog image
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace of the image
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogImage'
        '404':
          description: Image not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update catalog image
      description: Update an existing catalog image
      operationId: updateCatalogImage
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the catalog image
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace of the image
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCatalogImageRequest'
      responses:
        '200':
          description: Image successfully updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogImage'
        '404':
          description: Image not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Remove catalog image
      description: Remove an image from the catalog
      operationId: deleteCatalogImage
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the catalog image
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace of the image
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Image successfully removed from catalog
        '404':
          description: Image not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /publish:
    post:
      summary: Publish ImageBuild to catalog
      description: Promote a completed ImageBuild to the catalog
      operationId: publishImageBuild
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PublishImageBuildRequest'
      responses:
        '201':
          description: ImageBuild successfully published to catalog
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatalogImage'
        '400':
          description: Invalid request or ImageBuild not ready
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: ImageBuild not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /images/{name}/verify:
    post:
      summary: Verify catalog image
      description: Trigger manual verification of image registry accessibility
      operationId: verifyCatalogImage
      parameters:
        - name: name
          in: path
          required: true
          description: Name of the catalog image
          schema:
            type: string
        - name: namespace
          in: query
          description: Kubernetes namespace of the image
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Verification triggered successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerificationResponse'
        '404':
          description: Image not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    CatalogImage:
      type: object
      required:
        - metadata
        - spec
      properties:
        metadata:
          $ref: '#/components/schemas/ObjectMeta'
        spec:
          $ref: '#/components/schemas/CatalogImageSpec'
        status:
          $ref: '#/components/schemas/CatalogImageStatus'

    CatalogImageSpec:
      type: object
      required:
        - registryUrl
      properties:
        registryUrl:
          type: string
          description: Full URL to the image in the container registry
          pattern: '^([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}(:[0-9]{1,5})?/.*$'
          example: "quay.io/centos-automotive/autosd:cs9-rpi4-v1.0.0"
        digest:
          type: string
          description: Immutable content-addressable identifier
          pattern: '^sha256:[a-f0-9]{64}$'
          example: "sha256:abc123def456..."
        tags:
          type: array
          description: Mutable labels for categorization
          items:
            type: string
          example: ["production", "automotive", "embedded"]
        authSecretRef:
          $ref: '#/components/schemas/AuthSecretReference'
        verificationInterval:
          type: string
          description: How often to verify registry accessibility
          pattern: '^([0-9]+(\.[0-9]+)?(ns|us|µs|ms|s|m|h))+$'
          default: "1h"
        metadata:
          $ref: '#/components/schemas/CatalogImageMetadata'

    CatalogImageStatus:
      type: object
      properties:
        observedGeneration:
          type: integer
          description: Generation observed by the controller
        phase:
          type: string
          enum: [Pending, Verifying, Available, Unavailable, Failed]
          description: Current lifecycle phase
        conditions:
          type: array
          description: Detailed status conditions
          items:
            $ref: '#/components/schemas/Condition'
        registryMetadata:
          $ref: '#/components/schemas/RegistryMetadata'
        lastVerificationTime:
          type: string
          format: date-time
          description: When registry was last verified
        accessCount:
          type: integer
          description: Number of times this image has been accessed

    CatalogImageMetadata:
      type: object
      properties:
        architecture:
          type: string
          enum: [amd64, arm64]
          description: CPU architecture
        os:
          type: string
          default: "linux"
          description: Operating system
        variant:
          type: string
          description: Architecture variant
        distro:
          type: string
          description: Distribution identifier
          example: "cs9"
        distroVersion:
          type: string
          description: Distribution version
          example: "9.4"
        targets:
          type: array
          description: Compatible hardware targets
          items:
            $ref: '#/components/schemas/HardwareTarget'
        kernelVersion:
          type: string
          description: Kernel version in the image
          example: "6.1.0-rt"
        bootcCapable:
          type: boolean
          description: Whether this is a bootc-compatible image

    HardwareTarget:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Target hardware identifier
          enum: [qemu, raspberry-pi, beaglebone, intel-nuc]
        verified:
          type: boolean
          description: Whether image was tested on this target
          default: false
        notes:
          type: string
          description: Target-specific information

    RegistryMetadata:
      type: object
      properties:
        resolvedDigest:
          type: string
          description: Digest resolved from registry
        mediaType:
          type: string
          description: OCI manifest media type
        sizeBytes:
          type: integer
          format: int64
          description: Total image size in bytes
        layerCount:
          type: integer
          description: Number of image layers
        platform:
          $ref: '#/components/schemas/PlatformMetadata'

    PlatformMetadata:
      type: object
      properties:
        architecture:
          type: string
          description: Platform architecture
        os:
          type: string
          description: Platform operating system
        variant:
          type: string
          description: Platform variant

    AuthSecretReference:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the secret containing registry credentials
        namespace:
          type: string
          description: Namespace of the secret (defaults to image namespace)

    ObjectMeta:
      type: object
      properties:
        name:
          type: string
          description: Resource name
        namespace:
          type: string
          description: Resource namespace
        labels:
          type: object
          additionalProperties:
            type: string
          description: Resource labels
        annotations:
          type: object
          additionalProperties:
            type: string
          description: Resource annotations
        creationTimestamp:
          type: string
          format: date-time
          description: When the resource was created

    Condition:
      type: object
      required:
        - type
        - status
        - lastTransitionTime
      properties:
        type:
          type: string
          description: Condition type
        status:
          type: string
          enum: ["True", "False", "Unknown"]
          description: Condition status
        reason:
          type: string
          description: Reason for the condition
        message:
          type: string
          description: Human-readable message
        lastTransitionTime:
          type: string
          format: date-time
          description: Last time the condition changed
        observedGeneration:
          type: integer
          description: Generation when condition was set

    CatalogImageList:
      type: object
      required:
        - items
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/CatalogImage'
        metadata:
          $ref: '#/components/schemas/ListMeta'

    ListMeta:
      type: object
      properties:
        continue:
          type: string
          description: Continuation token for pagination
        remainingItemCount:
          type: integer
          description: Estimated remaining items

    CreateCatalogImageRequest:
      type: object
      required:
        - name
        - spec
      properties:
        name:
          type: string
          description: Name for the catalog image
        spec:
          $ref: '#/components/schemas/CatalogImageSpec'
        labels:
          type: object
          additionalProperties:
            type: string
          description: Labels to apply to the resource

    UpdateCatalogImageRequest:
      type: object
      required:
        - spec
      properties:
        spec:
          $ref: '#/components/schemas/CatalogImageSpec'
        labels:
          type: object
          additionalProperties:
            type: string
          description: Labels to update on the resource

    PublishImageBuildRequest:
      type: object
      required:
        - imageBuildName
        - imageBuildNamespace
      properties:
        imageBuildName:
          type: string
          description: Name of the ImageBuild to publish
        imageBuildNamespace:
          type: string
          description: Namespace of the ImageBuild
        catalogImageName:
          type: string
          description: Optional name for the catalog image (defaults to ImageBuild name)
        catalogImageNamespace:
          type: string
          description: Namespace for the catalog image (defaults to ImageBuild namespace)
        tags:
          type: array
          items:
            type: string
          description: Additional tags to apply to the catalog image
        metadata:
          $ref: '#/components/schemas/CatalogImageMetadata'
          description: Override metadata from ImageBuild

    VerificationResponse:
      type: object
      properties:
        message:
          type: string
          description: Verification status message
        triggered:
          type: boolean
          description: Whether verification was successfully triggered

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type
        message:
          type: string
          description: Error message
        details:
          type: object
          description: Additional error details

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - BearerAuth: []

tags:
  - name: Images
    description: Catalog image management
  - name: Publishing
    description: Image publication operations