apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: automotive-dev-operator-on-push
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" && target_branch == "main" && (
        files.all.exists(f, f.matches("^(api|internal|cmd)/.*")) ||
        files.all.exists(f, f.matches("^Dockerfile$")) ||
        files.all.exists(f, f.matches("^go\\.(mod|sum)$"))
      )
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/rh-sdv-cloud/automotive-dev-operator:{{revision_short}}"
    - name: output-image-tag
      value: "quay.io/rh-sdv-cloud/automotive-dev-operator:latest"
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: .
  pipelineSpec:
    params:
      - name: git-url
      - name: revision
      - name: output-image
      - name: output-image-tag
      - name: dockerfile
      - name: path-context
    results:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
    tasks:
      - name: clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
            - name: name
              value: git-clone
            - name: kind
              value: task
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: workspace
          - name: basic-auth
            workspace: git-auth
      
      - name: build-container-amd64
        runAfter:
          - clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
            - name: name
              value: buildah
            - name: kind
              value: task
        params:
          - name: IMAGE
            value: $(params.output-image)-amd64
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: HERMETIC
            value: "true"
          - name: PREFETCH_INPUT
            value: "gomod"
          - name: BUILD_ARGS
            value:
              - TARGETOS=linux
              - TARGETARCH=amd64
        workspaces:
          - name: source
            workspace: workspace
      
      - name: build-container-arm64
        runAfter:
          - clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
            - name: name
              value: buildah
            - name: kind
              value: task
        params:
          - name: IMAGE
            value: $(params.output-image)-arm64
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: HERMETIC
            value: "true"
          - name: PREFETCH_INPUT
            value: "gomod"
          - name: BUILD_ARGS
            value:
              - TARGETOS=linux
              - TARGETARCH=arm64
        workspaces:
          - name: source
            workspace: workspace
      
      - name: build-container
        runAfter:
          - build-container-amd64
          - build-container-arm64
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-build-image-manifest:0.1
            - name: name
              value: build-image-manifest
            - name: kind
              value: task
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: IMAGES
            value:
              - $(tasks.build-container-amd64.results.IMAGE_URL)@$(tasks.build-container-amd64.results.IMAGE_DIGEST)
              - $(tasks.build-container-arm64.results.IMAGE_URL)@$(tasks.build-container-arm64.results.IMAGE_DIGEST)
          - name: IMAGE_TAG
            value: $(params.output-image-tag)
      
      - name: scan-clair
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.1
            - name: name
              value: clair-scan
            - name: kind
              value: task
        params:
          - name: image-digest
            value: $(tasks.build-container.results.IMAGE_DIGEST)
          - name: image-url
            value: $(tasks.build-container.results.IMAGE_URL)
      
      - name: generate-sbom
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-generate-sbom:0.1
            - name: name
              value: generate-sbom
            - name: kind
              value: task
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
      
      - name: sign-image
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-cosign-sign:0.1
            - name: name
              value: cosign-sign
            - name: kind
              value: task
        params:
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
    
    workspaces:
      - name: workspace
      - name: git-auth
        optional: true
  
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"

