apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: automotive-dev-operator-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && (
        files.all.exists(f, f.matches("^(api|internal|cmd)/.*")) ||
        files.all.exists(f, f.matches("^Dockerfile$")) ||
        files.all.exists(f, f.matches("^go\\.(mod|sum)$")) ||
        files.all.exists(f, f.matches("^\\.tekton/automotive-dev-operator-.*\\.yaml$"))
      )
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/rh-sdv-cloud/automotive-dev-operator:pr-{{pull_request_number}}-{{revision_short}}"
    - name: dockerfile
      value: Dockerfile
    - name: path-context
      value: .
  pipelineSpec:
    params:
      - name: git-url
      - name: revision
      - name: output-image
      - name: dockerfile
      - name: path-context
    results:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
    tasks:
      - name: clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
            - name: name
              value: git-clone
            - name: kind
              value: task
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: workspace
          - name: basic-auth
            workspace: git-auth
      
      - name: build-container
        runAfter:
          - clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
            - name: name
              value: buildah
            - name: kind
              value: task
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
          - name: HERMETIC
            value: "true"
          - name: PREFETCH_INPUT
            value: "gomod"
          - name: BUILD_ARGS
            value:
              - TARGETOS=linux
              - TARGETARCH=amd64
        workspaces:
          - name: source
            workspace: workspace
      
      - name: scan-clair
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-clair-scan:0.1
            - name: name
              value: clair-scan
            - name: kind
              value: task
        params:
          - name: image-digest
            value: $(tasks.build-container.results.IMAGE_DIGEST)
          - name: image-url
            value: $(tasks.build-container.results.IMAGE_URL)
      
      - name: scan-snyk
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-snyk-check:0.1
            - name: name
              value: snyk-check
            - name: kind
              value: task
        params:
          - name: image-digest
            value: $(tasks.build-container.results.IMAGE_DIGEST)
        workspaces:
          - name: source
            workspace: workspace
      
      - name: deprecated-image-check
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-deprecated-image-check:0.1
            - name: name
              value: deprecated-image-check
            - name: kind
              value: task
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
      
      - name: sbom-json-check
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-sbom-json-check:0.1
            - name: name
              value: sbom-json-check
            - name: kind
              value: task
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
    
    workspaces:
      - name: workspace
      - name: git-auth
        optional: true
  
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"

