apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: catalog-on-pull-request
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" && (
        files.all.exists(f, f.matches("^catalog/.*")) ||
        files.all.exists(f, f.matches("^catalog\\.Dockerfile$")) ||
        files.all.exists(f, f.matches("^\\.tekton/catalog-.*\\.yaml$"))
      )
spec:
  params:
    - name: git-url
      value: "{{repo_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: "quay.io/rh-sdv-cloud/automotive-dev-operator-catalog:pr-{{pull_request_number}}-{{revision_short}}"
    - name: dockerfile
      value: catalog.Dockerfile
    - name: path-context
      value: .
  pipelineSpec:
    params:
      - name: git-url
      - name: revision
      - name: output-image
      - name: dockerfile
      - name: path-context
    results:
      - name: IMAGE_URL
        value: $(tasks.build-container.results.IMAGE_URL)
      - name: IMAGE_DIGEST
        value: $(tasks.build-container.results.IMAGE_DIGEST)
    tasks:
      - name: clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-git-clone:0.1
            - name: name
              value: git-clone
            - name: kind
              value: task
        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.revision)
        workspaces:
          - name: output
            workspace: workspace
          - name: basic-auth
            workspace: git-auth
      
      - name: build-container
        runAfter:
          - clone-repository
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-buildah:0.2
            - name: name
              value: buildah
            - name: kind
              value: task
        params:
          - name: IMAGE
            value: $(params.output-image)
          - name: DOCKERFILE
            value: $(params.dockerfile)
          - name: CONTEXT
            value: $(params.path-context)
        workspaces:
          - name: source
            workspace: workspace
      
      - name: validate-catalog
        runAfter:
          - build-container
        taskRef:
          resolver: bundles
          params:
            - name: bundle
              value: quay.io/konflux-ci/tekton-catalog/task-opm-validate:0.1
            - name: name
              value: opm-validate
            - name: kind
              value: task
        params:
          - name: IMAGE_URL
            value: $(tasks.build-container.results.IMAGE_URL)
          - name: IMAGE_DIGEST
            value: $(tasks.build-container.results.IMAGE_DIGEST)
    
    workspaces:
      - name: workspace
      - name: git-auth
        optional: true
  
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"

